### ISSUE TITLE
NoSuchFieldError with jaxws-maven-plugin

### ISSUE THREAD

**Issue by kermit-the-frog** [dmak/jaxb-xew-plugin#29]
I can't get the jaxb-xew-plugin to work with maven version 3.2.1 and jaxws-maven-plugin version 2.3.

All I get is

Exception in thread "main" java.lang.ClassCastException: java.lang.NoSuchFieldError cannot be cast to java.lang.Exception
    at org.jvnet.jax_ws_commons.jaxws.Invoker.main(Invoker.java:87)

Any ideas?
kermit-the-frog

**Comment by dschulten** [comment]
@dmak has written a blog post [maven-jaxb2-plugin: java.lang.NoSuchFieldError: encoding](https://pw999.wordpress.com/2016/01/05/maven-jaxb2-plugin-java-lang-nosuchfielderror-encoding/) which explains for the maven-jaxb2-plugin how to exclude the jaxb-xjc dependency, which can also pull in other dependencies that no longer match the maven-jaxb2-plugin or the jaxws-maven-plugin, causing various NoClassDefFound, NoSuchFieldError, NoSuchMethodError etc. with istack, xjc etc.

The same exclusion works when using jaxws-maven-plugin 2.5. This may not do the trick if an older xjc plugin simply no longer works with dependencies used by a current jaxws-maven-plugin or maven-jaxb2-plugin, but in many cases excluding the old xjc can help.
In my case the jaxb-fluent-api plugin was the offender:

	<plugin>
		<groupId>org.codehaus.mojo</groupId>
		<artifactId>jaxws-maven-plugin</artifactId>
		<version>2.5</version>
		<dependencies>
			<dependency>
				<groupId>net.java.dev.jaxb2-commons</groupId>
				<artifactId>jaxb-fluent-api</artifactId>
				<version>2.1.8</version>
				<exclusions>
					<exclusion>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-xjc</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.jvnet.jaxb2_commons</groupId>
				<artifactId>jaxb2-basics</artifactId>
				<version>0.12.0</version>
			</dependency>
		</dependencies>
		<executions>
			<execution>
				<goals>
					<goal>wsimport</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<xjcArgs>
				<xjcArg>-Xfluent-api</xjcArg>
				<xjcArg>-XsimpleEquals</xjcArg>
			</xjcArgs>
			<xadditionalHeaders>true</xadditionalHeaders>
			<wsdlDirectory>src/main/resources/wsdl</wsdlDirectory>
			<wsdlLocation>/wsdl/my.wsdl</wsdlLocation>
			<packageName>my.soapclient</packageName>
		</configuration>
	</plugin

**Comment by dmak** [comment]
Pity that developers have to spent time trying to integrate modules from, I would say, different epochs. The above mentioned [` jaxb-fluent-api v2.1.8`](https://repo1.maven.org/maven2/net/java/dev/jaxb2-commons/jaxb-fluent-api/2.1.8/) is from 2010 (as well as [`property-listener-injector v1.0`](https://repo1.maven.org/maven2/org/jvnet/jaxb2-commons/property-listener-injector/1.0/)), I am surprised that it still runs. One should make an effort and recompile it with newer `jaxb-xjc` API.

Except that I don't see any way out from the situation when one need to run "legacy" code under new "umbrella". 

Just checked that `jaxb-xjc` is now in early 2.4.x stage, so very soon there will be a demand to migrate `jaxb-xew-plugin` to that API and that could trigger a dependency nightmare.
